c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: true
uniform_prob: 0.0
reset_optimizer: true
batch_size_training: 32
gradient_accumulation_steps: 1
num_epochs: 25
lr: 0.0001
weight_decay: 0.01

