project: coconut
seed: 0
debug: false
bf16: false
resume: 40
save_only_improve: false
load_model_path: null
only_eval: true
name: prosqa-coconut
save_path: outputs/prosqa/default
wandb_entity: tml-coconut

resume_mode: auto
resume_attempt_id: null
signature_ignore_keys: []

